// Section exports
export { Hero } from "./Hero"
export { Features } from "./Features"
export { WhyChoose } from "./WhyChoose"
export { Advantage } from "./Advantage"
export { EmpoweringTransformations } from "./EmpoweringTransformations"
export { CourseHighlights } from "./CourseHighlights"
export { EliteTeachers } from "./EliteTeachers"
export { Testimonials } from "./Testimonials"
export { VideoSection } from "./VideoSection"
export { FAQ } from "./FAQ"
export { ZohoFormSection } from "./ZohoFormSection"
export { Courses } from "./Courses"
export { Teachers } from "./Teachers"
export { CTABanner } from "./CTABanner"
export { Footer } from "./Footer"
